openapi: 3.1.3
info:
  title: Ping Pong
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /ping:
    get:
      responses:
        200:
          description: pong
          content:
            text/plain:
              schema:
                type: string
                example: pong